include: package:pedantic_mono/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors: 
    sort_pub_dependencies: false
    file_names: false
    invalid_annotation_target: false
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

    